apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cast-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: cast-db
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "cast_db_username"
            - name: POSTGRES_PASSWORD
              value: "cast_db_password"
            - name: POSTGRES_DB
              value: "cast_db_dev"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: cast-db-storage
      volumes:
        - name: cast-db-storage
          persistentVolumeClaim:
            claimName: cast-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cast-db
spec:
  selector:
    app: cast-db
  ports:
    - port: 5432
      targetPort: 5432
